
# ------------- #
# `config.toml` #
# ------------- #

baseURL = "https://tasteful.netlify.com/"
languageCode = "en-us"

title = "TT by Traci"
theme="tt"
summaryLength = "7"

# -------------------------------- #

# Main Menu Nav Items

[menu]
	
	[[menu.nav]]
    name = "Home"
    URL = "hero-area"
    weight = 1

    [[menu.nav]]
    name = "About"
    URL = "about-us"
    weight = 2

    [[menu.nav]]
    name = "Testimonials"
    URL = "testimonials"
    weight = 3

    [[menu.nav]]
    name = "Process"
    URL = "process"
    weight = 4

    [[menu.nav]]
    name = "News"
    URL = "subscribe"
    weight = 5

    [[menu.nav]]
    name = "Contact Us"
    URL = "contact-us"
    weight = 6

# -------------------------------- #

# Global Settings

# [params]
# logo = "images/logo.png"


[params.heroArea]
enable = true
[params.heroImg ] 
url =  "images/header.jpg"

# -------------------------------- #

## Gallery Items

[params.gallery]
enable = true
title= "Featured <span>Gallery</span>"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

# -------------------------------- #

## About Section

[params.about]
enable = true
title= "Traci's <span>Vision</span>"
bgImage = "images/avatar-img.jpg"
description = "Through Strength and Wisdom I create Serenity.  We all have areas of the home that tend to bring us down.  Either through clutter, disorganisation or old memories that we know it's time to part with. I come in, offer some suggestions, and together we will make your areas inspiring, new, and refreshing. Or, if you are relocating, I can help transform your new house into a welcoming home!"


# -------------------------------- #

## Testimonials Section

[params.testimonials]
enable = true
title = "Customer <span>Testimonials</span>"

# -------------------------------- #

## Process Section

[params.process]
enable = true
title = "Our Easy <span>Process</span>"
description= " Through my easy three-step process, I provide a service which transforms kitchens, bathrooms, and laundries into well-organised spaces that help you enjoy spending time in your home."

[[params.process.item]]
title = "Step One: Consultation"
description= "My services begin with an in-home consultation where we make a plan catered to your needs and lifestyle. We determine which spaces need a touch of love, which spaces are most important to you, and how involved you would like to be in the transformation process."
#price = "$ 100.00"

[[params.process.item]]
title = "Step Two: Visualisation"
description= "After we have a basic plan, we move into the visualisation stage. Here we begin by using various forms of media to illustrate your ideal space. After careful consideration of your 'must-haves' we will agree on a budget so that we can begin transforming your visualisation into a realisation!"
#price = "$ 125.00"

[[params.process.item]]
title = "Step Three: Realisation"
description= "We conclude our transformation process by bringing your expectations to reality. Here I will purchase anything from spices and detergents to pans and appliances for your new space. All organisation and installation of any new products will be done for you so that you can dive into loving your new space!"
#price = "$ 150.00"


# -------------------------------- #

## Subscription Section

[params.subscription]
enable = true
title= "Subscribe to our <span>Newsletter</span>"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"

### Mailchimp subscription configuration 
formAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e"
formName = "b_f95ece2732a6e9925f2e70a61_b1e227529e"

# -------------------------------- #

## Contact Section 

[params.contact]
enable = true
title= "<span>Contact Us</span>"
subtitle= "SIGN UP FOR EMAIL ALERTS"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"

# -------------------------------- #

## Footer Section 

[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
# blogTitle = "LATEST <span>BLOG POSTS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

[[params.footer.contactItem]]
title="Telephone"
icon = "fa fa-phone"
content = "Traci Holzheimer: +64 21 686 887"

# [[params.footer.contactItem]]
# title="Address"
# icon = "fa fa-map-marker"
# content = "2046 Blue Spruce Lane Laurel Canada"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "Traci Holzheimer: tastefultransformations.nz@gmail.com"

[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"


[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"

# -------------------------------- #

## Footer Copyright Text

[params.footerCopyright]
enable = true
Text = "Copyright 2019 - All Rights Reserved."

# Design and Developed By Themefisher.com"

# -------------------------------- #


# EOF #

